ItCompanyTaskManager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("TaskManager.urls", namespace="TaskManager")),
    path("accounts/", include("django.contrib.auth.urls")),
]

TaskManager/urls.py
from django.urls import path

from TaskManager.views import (
    index,
    RegisterUser,
    LoginUser,
    LogoutUser,
    RegisterDone,
    WorkerDetailView,
    WorkerDeleteView,
    WorkerUpdateView,
    WorkerListView,
    TaskListView,
    TaskDetailView,
    TaskUpdateView,
    TaskDeleteView,
    task_complete_view,
    TaskCreateView
)

urlpatterns = [
    path("", index, name="index"),
    path("login/", LoginUser.as_view(), name="login"),
    path("register/", RegisterUser.as_view(), name="register"),
    path("logout/", LogoutUser.as_view(), name="logout"),
    path("done/<str:name>", RegisterDone.as_view(), name="done"),
    path("worker/<slug:slug>", WorkerDetailView.as_view(), name="worker-detail"),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path("worker/<slug:slug>/delete/", WorkerDeleteView.as_view(), name="worker-delete"),
    path("worker/<slug:slug>/update/", WorkerUpdateView.as_view(), name="worker-update"),
    path("tasks/", TaskListView.as_view(), name="tasks-list"),
    path("tasks/<int:pk>", TaskDetailView.as_view(), name="tasks-detail"),
    path("tasks/complate/<int:pk>", task_complete_view, name="task-complete"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/update", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete", TaskDeleteView.as_view(), name="task-delete"),

]

app_name = "TaskManager"

TaskManager/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

from ItCompanyTaskManager import settings


class TaskType(models.Model):
    name = models.CharField(max_length=63)

    def __str__(self):
        return f"{self.name}"


class Position(models.Model):
    name = models.CharField(max_length=63)

    def __str__(self):
        return f"{self.name}"


class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class Worker(AbstractUser):
    position = models.ForeignKey(to=Position, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=63, unique=True)

    email = models.EmailField('email address', unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.username)

        return super(Worker, self).save(*args, **kwargs)

    def get_absolute_url(self):
        kwargs = {
            "slug": self.slug
        }
        return reverse('TaskManager:worker-detail', kwargs=kwargs)

    class Meta:
        verbose_name = "worker"
        verbose_name_plural = "workers"

    def __str__(self):
        return f"{self.username}({self.first_name} {self.last_name})"

    objects = UserManager()


class Task(models.Model):
    PRIORITY_CHOICES = [
        ("U", "Urgent"),
        ("H", "High"),
        ("M", "Medium"),
        ("L", "Low"),
    ]

    name = models.CharField(max_length=63)
    description = models.TextField(max_length=255)
    deadline = models.DateTimeField()
    is_completed = models.BooleanField()
    priority = models.CharField(max_length=1, choices=PRIORITY_CHOICES)
    task_type = models.ForeignKey(to=TaskType, on_delete=models.CASCADE)
    assignees = models.ManyToManyField(to=Worker, related_name="tasks")
    created_ad = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

    class Meta:
        ordering = ["is_completed", "created_ad"]

    def __str__(self):
        return f"{self.name}( type:{self.task_type},priority {self.priority})"

TaskManager/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from TaskManager.models import Worker, Task


class WorkerCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Worker
        fields = UserCreationForm.Meta.fields + (
            "email",
            "first_name",
            "last_name",
            "position"
        )


class TaskCreateForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["name", "description", "task_type", "is_completed", "assignees", "deadline", "priority"]


class TaskUpdateForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["name", "description", "task_type", "is_completed", "assignees", "deadline", "priority"]


class WorkerUpdateForm(forms.ModelForm):
    class Meta:
        model = Worker
        fields = ["first_name", "last_name", "position"]

TaskManager/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from TaskManager.forms import WorkerCreationForm, WorkerUpdateForm, TaskCreateForm, TaskUpdateForm

from TaskManager.models import Worker, Task


@login_required
def index(request):
    """View function for the home page of the site."""
    num_workers = Worker.objects.count()
    num_task = Task.objects.count()

    context = {
        "num_workers": num_workers,
        "num_task": num_task,
    }
    return render(request, "TaskManager/index.html", context=context)


class RegisterUser(generic.CreateView):
    model = Worker
    form_class = WorkerCreationForm
    template_name = "account/register.html"
    success_url = reverse_lazy('TaskManager:done')

    def get_success_url(self):
        return reverse_lazy("TaskManager:done", kwargs={"name": self.object.username})


class WorkerListView(LoginRequiredMixin, generic.ListView):
    model = Worker
    template_name = "TaskManager/worker_list.html"
    paginate_by = 2


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Worker
    template_name = "account/worker_detail.html"


class WorkerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Worker
    form_class = WorkerUpdateForm
    success_url = reverse_lazy('TaskManager:worker_detail')
    template_name = "account/worker_update.html"

    def get_success_url(self):
        return reverse_lazy("TaskManager:worker_detail", kwargs={"slug": self.object.slug})


class WorkerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Worker
    success_url = reverse_lazy("TaskManager:index")
    template_name = "account/worker_delete.html"


class LoginUser(LoginView):
    form_class = AuthenticationForm
    template_name = "registration/login.html"

    def get_success_url(self):
        return reverse_lazy('TaskManager:index')


class LogoutUser(LogoutView):
    template_name = "account/logout.html"


class RegisterDone(LoginView):
    template_name = "account/register_done.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["username"] = self.kwargs["name"]
        return context


class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    template_name = "TaskManager/task_list.html"
    paginate_by = 5


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task
    template_name = "TaskManager/task_detail.html"


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = TaskUpdateForm
    success_url = reverse_lazy("TaskManager:tasks-detail")
    template_name = "TaskManager/task_update.html"

    def get_success_url(self):
        return reverse_lazy("TaskManager:tasks-detail", kwargs={"pk": self.object.id})


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskCreateForm
    template_name = "TaskManager/task_create.html"
    success_url = reverse_lazy("TaskManager:tasks-list")

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    template_name = "TaskManager/confirm_delete_task.html"
    success_url = reverse_lazy("TaskManager:tasks-list")


@login_required
def task_complete_view(request, pk):
    task = Task.objects.get(id=pk)
    if task.is_completed:
        task.is_completed = False
    else:
        task.is_completed = True
    task.save()
    return HttpResponseRedirect(reverse_lazy("TaskManager:tasks-list"))

templates/TaskManager/confirm_delete_task.html
{% extends "base.html" %}

{% block content %}
    <h1>Delete Task?</h1>
    <p>Are you really want to delete <strong>{{ task.name }}</strong>?</p>
    <form action="" method="post">
      {% csrf_token %}

      <input type="submit" value="Yes" class="btn btn-danger">
      <a class="btn btn-secondary" href="{% url 'TaskManager:tasks-detail' pk=task.id %}">No, thanks</a>
    </form>
{% endblock %}

templates/TaskManager/index.html
{% extends 'base.html' %}
{% block content %}
    <h1>Task manager Home</h1>
    <ul>
        <li ><strong>Workers:</strong> {{ num_workers }}</li>
        <li><strong>Tasks:</strong> {{ num_task }}</li>
    </ul>
{% endblock %}

templates/TaskManager/task_create.html
{% extends 'base.html' %}
{% block content %}
  <h1>Create Task</h1>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
    </form>
{% endblock %}

templates/TaskManager/task_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Task: {{ task.name }}
    <a href="{% url 'TaskManager:task-delete' pk=task.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'TaskManager:task-update' pk=task.id %}" class="btn btn-secondary link-to-page">
      Update task
    </a>
  </h1>

  <p><strong>Description:</strong> {{ task.description }}</p>
  <p><strong>Deadline:</strong> {{ task.deadline }}</p>
  <p><strong>Is_completed:</strong> {{ task.is_completed }}</p>
  <p><strong>Priority:</strong> {{ task.get_priority_display }}</p>
  <p><strong>Task_type:</strong> {{ task.task_type }}</p>
  {% for worker in task.assignees.all %}
     <p><strong>Assignees:</strong> {{ worker.username }}</p>
  {% endfor %}
  <p><strong>Created_by:</strong> {{ task.created_by }}</p>


  <p><strong>Created_ad:</strong> {{ task.created_ad }}</p>






{% endblock %}

templates/TaskManager/task_list.html
{% extends "base.html" %}

{% block content %}
    <h1>
    Task list
    <a href="{% url 'TaskManager:task-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>
  {% if task_list %}


  {% for task in task_list %}
    <p>
      <strong>
        {{ task.name }}
        {% if task.is_completed %}
          <span class="text-success">Done</span>
        {% else %}
          <span class="text-danger">Not done</span>
        {% endif %}
      </strong>
    </p>
    {%  if task.is_completed %}
      <a href="{% url 'TaskManager:task-complete' pk=task.id %}" class="btn btn-dark link-to-page">Undo</a>
    {% else %}
      <a href="{% url 'TaskManager:task-complete' pk=task.id %}" class="btn btn-success link-to-page">Compete</a>
    {% endif %}
    <p>
      Created: {{ task.created_ad }}
      {% if task.deadline %}
        Deadline: {{ task.deadline }}
      {% endif %}
       <a href="{% url 'TaskManager:tasks-detail' pk=task.id %}" class="btn btn-secondary link-to-page">
      View details
    </a>
    </p>
    {% endfor %}
    {% else %}
      <p>Empty =(</p>
    {% endif %}

{% endblock %}

templates/TaskManager/task_update.html
{% extends "base.html" %}


{% block content %}
  <h1>Update Task </h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/TaskManager/worker_list.html
{% extends "base.html" %}

{% block content %}
    <h1>
      Worker list
    </h1>


    {% if worker_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Position</th>
      </tr>
    {% for worker in worker_list %}
      <tr>
        <td>{{ worker.id }}</td>
        <td>{% if user == worker%}
          <a href="{{ worker.get_absolute_url }}">{{ worker.username }}
        {% else %}
          {{ worker.username }}
        {% endif %}</a></td>
        <td>{{ worker.first_name }}</td>
        <td>{{ worker.last_name }}</td>
        <td>{{ worker.position }}</td>
      </tr>
    {% endfor %}

    </table>
    {% else %}
      <p>There are no workers in the service.</p>
    {% endif %}
{% endblock %}