ItCompanyTaskManager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("TaskManager.urls", namespace="TaskManager")),
    path("accounts/", include("django.contrib.auth.urls")),
]

TaskManager/urls.py
from django.urls import path

from TaskManager.views import (
    index,
    RegisterUser,
    LoginUser,
    LogoutUser,
    RegisterDone,
    WorkerDetailView,
    WorkerDeleteView,
    WorkerUpdateView,
    WorkerListView,
    TaskListView,
    TaskDetailView,
    TaskUpdateView,
    TaskDeleteView,
    task_complete_view,
    TaskCreateView
)

urlpatterns = [
    path("", index, name="index"),
    path("login/", LoginUser.as_view(), name="login"),
    path("register/", RegisterUser.as_view(), name="register"),
    path("logout/", LogoutUser.as_view(), name="logout"),
    path("done/<str:name>", RegisterDone.as_view(), name="done"),
    path("worker/<slug:slug>", WorkerDetailView.as_view(), name="worker-detail"),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path("worker/<slug:slug>/delete/", WorkerDeleteView.as_view(), name="worker-delete"),
    path("worker/<slug:slug>/update/", WorkerUpdateView.as_view(), name="worker-update"),
    path("tasks/", TaskListView.as_view(), name="tasks-list"),
    path("tasks/<int:pk>", TaskDetailView.as_view(), name="tasks-detail"),
    path("tasks/complate/<int:pk>", task_complete_view, name="task-complete"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/update", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete", TaskDeleteView.as_view(), name="task-delete"),

]

app_name = "TaskManager"

templates/includes/footer.html
<footer class="bg-light text-center text-lg-start fixed-bottom">
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2020 Copyright:
    <a class="text-dark" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>

templates/includes/navigation.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <span class="navbar-brand">TM</span>
{#    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">#}
{#      <span class="navbar-toggler-icon"></span>#}
{#    </button>#}
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'TaskManager:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'TaskManager:tasks-list' %}">Task</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'TaskManager:worker-list' %}">Workers</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            {% if user.is_authenticated %}
              {{ user.username }}
          </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{{ user.get_absolute_url}}">Details</a></li>
                <li><a class="dropdown-item" href="{% url 'TaskManager:logout' %}">Logout</a></li>
              </ul>
            {% else %}
              <li class="nav-item"><a class="nav-link" href="{% url 'TaskManager:login' %}">Login</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'TaskManager:register' %}">Registration</a></li>
            {% endif %}
      </ul>

    </div>
  </div>

</nav>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}